
INSERT INTO PESSOA(nome, DATA_NASCIMENTO, logradouro, cep, numero, cidade) VALUES('MARCELO PILAR', '03/03/1988', 'RUA FREDERICO', '99999', 170, 'RECIFE');

INSERT INTO PESSOA(nome, DATA_NASCIMENTO, logradouro, cep, numero, cidade) VALUES('MARIO PILAR', '02/07/1986', 'RUA DONA ELVIRA', '88888', 200, 'OLINDA');

INSERT INTO PESSOA(nome, DATA_NASCIMENTO, logradouro, cep, numero, cidade) VALUES('CONCEICAO PESSOA', '23/12/1963', 'RUA DONA ELVIRA', '777', 201, 'IGARASSU');
